# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0026_auto_20170609_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ВНИМАНИЕ! ИСПОЛЬЗОВАТЬ ТОЛЬКО ЛАТИНСКИЕ БУКВЫ', max_length=50, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('name_spider', models.CharField(help_text='ВНИМАНИЕ! ИСПОЛЬЗОВАТЬ ТОЛЬКО ЛАТИНСКИЕ БУКВЫ', max_length=50, verbose_name='Имя паука')),
                ('archive', models.FileField(upload_to='spiders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Zip-архив с пауком')),
                ('interval', models.IntegerField(help_text='В минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал перед запусками')),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('last_run', models.DateTimeField(blank=True, verbose_name='Последний запуск')),
                ('is_unpacked', models.BooleanField(default=False, verbose_name='Распакован')),
                ('path', models.FilePathField(allow_folders=True, blank=True, help_text='Если не распакован то пустой', verbose_name='Путь к папке с пауком')),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Site')),
            ],
            options={
                'verbose_name': 'Паук',
                'verbose_name_plural': 'Пауки',
                'db_table': 'spiders',
            },
        ),
    ]
