# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_auto_20170619_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='name_spider',
        ),
        migrations.AlterField(
            model_name='spider',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Рабочий'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='name',
            field=models.CharField(help_text='ВНИМАНИЕ! ИСПОЛЬЗОВАТЬ ТОЛЬКО ЛАТИНСКИЕ БУКВЫ', max_length=50, verbose_name='Имя паука'),
        ),
    ]
