# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0003_auto_20170619_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск'),
        ),
    ]
