# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0004_auto_20170619_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='path',
            field=models.CharField(blank=True, help_text='Если не распакован то пустой', max_length=500, verbose_name='Путь к папке с пауком'),
        ),
    ]
