# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20170430_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageposition',
            name='number',
        ),
        migrations.AddField(
            model_name='pageposition',
            name='index',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.TextField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='layout',
            field=models.IntegerField(choices=[(1, 'horizontal'), (2, 'vertical')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.PagePosition', verbose_name='Позиция на странице'),
        ),
        migrations.AlterField(
            model_name='pageposition',
            name='type',
            field=models.IntegerField(choices=[(1, 'horizontal'), (2, 'vertical')], verbose_name='Тип позиции'),
        ),
        migrations.AlterField(
            model_name='views',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='banners.Banner', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='views',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
