# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170501_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterModelTable(
            name='article',
            table='news',
        ),
    ]
