# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20170503_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Если указать то при сохранении будет закачен файл', verbose_name='Url картинки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
