# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20170503_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Если указать то при сохранении будет закачен файл', max_length=500, verbose_name='Url картинки'),
        ),
    ]
