# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20170503_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Если не указано то ставим текущую дату', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Если указать то при сохранении будет закачан файл', max_length=500, verbose_name='Url картинки'),
        ),
    ]
