# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20170505_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если скрытая то неотображается в меню сайта', verbose_name='Скрытая'),
        ),
    ]
