# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_category_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(unique=True, verbose_name='Источник статьи'),
        ),
    ]
