# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20170607_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', to_field='slug', verbose_name='Категория'),
        ),
    ]
