# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20170608_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='article',
            name='view_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='число просмотров'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='ЧПУ'),
        ),
    ]
