# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20170609_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
    ]
